### ISSUE TITLE
Create new Stock Control Purchase

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#121]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/8rRz4pkM7z

**Note:**
1. pls use fixture to create products, so you can select some in Stock Control Purchase
2. Customer Features for products and production plants needed

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] run your test in jenkins e2e on a vanilla db
    - https://dev589.metasfresh.com/
- [x] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
    - https://dashboard.cypress.io/#/projects/5yp4q1/runs/312/specs
- [x] get it integrated into `master`
  - [x] https://github.com/metasfresh/metasfresh-e2e/pull/151 (2019-07-11 - ts)
    - [x] https://github.com/metasfresh/metasfresh-e2e/pull/151#pullrequestreview-260926656

All Flags are ticked? Congratulations, you have delivered!

### todo

> checked with mark: we will probably change / add sth about this functionality once SPV is starting with WebUI; for now we can create the cypress test as it is, so: create a new entry there with some lines, run the process w/o errors and that's it
