### ISSUE TITLE
Change warehouse in material receipt candidate

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#153]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

http://recordit.co/IGc7i3uLDx

**Note:**
video includes the creation of material receipt and check if the warehouse is set correctly there: main part for this test is just changing the warehouse in the receipt candidate, though.

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] run your test in jenkins e2e on a vanilla db
    - https://dev627.metasfresh.com
- [ ] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
    - https://dashboard.cypress.io/#/projects/5yp4q1/runs/435/specs
- [ ] get it integrated into `master`
  * [ ] https://github.com/metasfresh/metasfresh-e2e/pull/251
    - https://github.com/metasfresh/metasfresh-e2e/pull/251#pullrequestreview-271115431

All Flags are ticked? Congratulations, you have delivered!

# todo

Use the 2 existing warehouses: `Hauptlager` and `Lager für Streckengeschäft`
- move from `Hauptlager` to `Lager für Streckengeschäft`

Create Purchase Order
- ensure warehouse is `Hauptlager`
- 1 product
- completed

Visit `Material Receipt Candidates` for the product (not packing item!)
- ensure warehouse is `Hauptlager`

Change the warehouse in advanced edit
- use the field `Warehouse Override` and change to `Lager für Streckengeschäft`
- ensure warehouse is still `Hauptlager` (unchanged)

Go back to the filtered view of `Material Receipt Candidates` and execute default quick-action (`quickAction_WEBUI_M_ReceiptSchedule_ReceiveHUs_UsingDefaults`)
- execute default quick-action (`quickAction_WEBUI_M_HU_CreateReceipt_NoParams`)

From Purchase Order visit `Material Receipt`
- expect only 1 row
- the warehouse should be `Lager für Streckengeschäft`
