### ISSUE TITLE
Create Material Tracking

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#167]
**Test shall include:**

- Customer Fixtures to use: (if needed): products, Lagerkonferenz (Karotten), bpartner
- What to test:

1. create Material Tracking, with Parzelle "Industriestrasse"
2. select "Karotten Abrechnung ohne Lager" / "Karotten Abrechnung mit Lager" 
- Expectation for the test to be successful

1. contract period can be set
2. "Karotten Abrechnung ohne Lager" / "Karotten Abrechnung mit Lager"  selectable
3. Material Tracking can be selected in PO

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] run your test in jenkins e2e on a vanilla db
- [ ] jenkins console URL / cypress dashboard URL to the successful test run (alternatively screenshot)
- [ ] get it integrated into `master`
  * [ ] (pull request URL)

All Flags are ticked? Congratulations, you have delivered!
