### ISSUE TITLE
Fix regex matching inside "writeIntoLookupListField" to match search modals

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh-e2e#276]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [ ] run your test in jenkins e2e on a vanilla db
- [ ] jenkins console URL / cypress dashboard URL to the successful test *suite* run (not just yours)
- [ ] get it integrated into `master`
  * [ ] (pull request URL)

All Flags are ticked? Congratulations, you have delivered!

# todo 

Fix regex matching inside `writeIntoLookupListField` to match search modals. I expect it to work with the regexp below!

```
the request: GET http://localhost:8080/rest/api/documentView/540189/540189-C/filter/default/field/M_Product_ID/typeahead?query=Product_05T11_04_26_553
cy.writeIntoLookupListField('M_Product_ID', productName, productName, false, false, '/rest/api/documentView/.*/filter/default/field/');
```

But it seems it waits for a `PATCH` instead.
If `PATCH` is changed to `GET` inside `writeIntoLookupListField`, it still won't work but this time errors out in `cy.waitForFieldValue`.

### Code example:

```javascript
it('Visit HU Editor, filter for the product, and expect a single row', function() {
    cy.visitWindow(540189);
    toggleNotFrequentFilters();
    selectNotFrequentFilterWidget('default');
    cy.writeIntoLookupListField('M_Product_ID', productName, productName, false, false, '/rest/api/documentView/.*/filter/default/field/');
    applyFilters();

    cy.expectNumberOfRows(1);
});
```
